// Chat API contract (INTERFACES.md #1, owner: arturo), the customer-visible case (#3) and the
// analyst console contract (docs/contrato_consola.md; #6 report shape owned by andres).
// Single source of truth for the front end; the Python backend mirrors these shapes
// (src/conversation/contract.py). Change both together.
// Conventions: snake_case fields, opaque string IDs, money as decimal string + ISO 4217
// currency, timestamps ISO 8601 UTC.

export type Language = "es" | "pt";
export type Lane = "A" | "B" | "C";

export type DemoKey = "lucia" | "sofia" | "andres" | "joao" | "martina" | "carlos";

// ---------- GET /health ----------
export interface HealthResponse {
  status: "ok";
  stage: string | null;
  deps: "ok" | "missing";
  // Factor of the judge switch fast_clock on this server (the local lifecycle's
  // LOCAL_SLA_SCALE, 1/1440 by default: 1 day = 1 minute). null where there is no demo clock
  // (LIFECYCLE_BACKEND=stepfunctions, or the dependencies are missing). The judge panel and
  // the console's Historial say this scale; a server without the field reads as null.
  demo_clock_scale: number | null;
}

// ---------- POST /session ----------
export interface SessionRequest {
  demo_key: DemoKey;
  channel: "web" | "app" | "whatsapp";
  language?: Language;
}

export interface SessionCustomer {
  display_name: string; // first name only, synthetic
  language: Language;
  locale: string; // es-MX, es-CO, es-AR, pt-BR
  country: "MX" | "CO" | "AR";
}

export interface SessionResponse {
  session_token: string; // opaque; send as Authorization: Bearer <token>
  expires_at: string; // ISO 8601 UTC
  customer: SessionCustomer;
  welcome: ChatTurn; // first system message with quick-start buttons
  synthetic: true;
}

// ---------- POST /chat ----------
// At most one of message or button_id. A request with neither is valid only when it carries
// demo_switches (a "switches only" request, see DemoSwitchesPatch).
export interface ChatRequest {
  client_msg_id: string; // uuid generated by the client; same id = same answer, never a second case
  message?: string; // max 1000 characters
  button_id?: string; // opaque id issued by the server in a previous turn
  demo_switches?: DemoSwitchesPatch; // judge-mode failure switches (RF-22), applied server side
}

// Failure switches of the judge mode (RF-22, plan section 12). They belong to the session and
// hold from the request that carries them (applied before its message or button).
// - Only the keys present change; at least one key must be present.
// - expire_session: true ends the session at once: this request and every later one answer
//   401 session_expired (a message or button in the same request is not processed).
//   expire_session: false is a no-op.
// - Switches only (no message, no button_id): the server answers a short template
//   ChatResponse confirming the switch WITHOUT advancing the conversation: `turn` repeats the
//   last turn number (it does not count toward the 30-turn cap), `buttons` is [] while the
//   buttons already pending stay valid (the UI keeps showing them), progress, case_card and
//   lane are the current ones, degraded is [], trace_summary has one rule step "demo_switches".
export interface DemoSwitchesPatch {
  tools_down?: boolean; // every gateway tool fails -> two retries, then lane C tool_failure
  model_slow?: boolean; // G1 exceeds LLM_TIMEOUT_SECONDS -> template reply, degraded model_timeout
  expire_session?: boolean; // true: the session expires now (401 session_expired)
  // Demo clock: the SLA timers of this session's lane B cases run 1440 times faster (1 day =
  // 1 minute; `local_api.py --sla-scale` changes the factor). Applies to the case already
  // open in the session and to the ones it opens later, never to other sessions. Promised
  // dates (expected_date, first_response_by) do not change. Does not exist in production.
  fast_clock?: boolean;
}

// Switch state of the session, echoed in every ChatResponse.
export interface DemoSwitchState {
  tools_down: boolean;
  model_slow: boolean;
  fast_clock: boolean;
}

export type ButtonKind = "confirm" | "deny" | "choice" | "handoff";

export interface ChatButton {
  id: string; // opaque, server-issued, single use
  label: string; // already in the reply language
  kind: ButtonKind;
}

export type ProgressStep = "understand" | "find" | "verify" | "case_open" | "done";

export interface ClaimedSlots {
  amount: string | null; // what the customer said, unverified
  currency: string | null;
  date: string | null; // ISO date or null
  merchant_text: string | null;
  card_last4: string | null;
}

export interface Progress {
  step: ProgressStep;
  complaint_type: "unrecognized_charge" | "wrong_fee" | "app" | "branch" | "service" | null;
  claimed: ClaimedSlots;
  missing: string[]; // slot names still needed
}

export type TraceActor = "rule" | "model" | "tool" | "human";

export interface TraceStep {
  actor: TraceActor;
  name: string; // e.g. "classify", "extract", "g1_extract", "find_candidate_txns", "lane_rules"
  latency_ms: number;
  version: string | null; // model, prompt or rules version
  error_code: string | null;
}

export interface TraceSummary {
  steps: TraceStep[];
  latency_ms: number; // server time for the whole turn
  cost_usd: number; // with the mock provider (LLM_PROVIDER=mock) an ESTIMATE from list prices
  model_id: string | null; // null when no model was called ("mock-g1" for the local mock)
  tokens_in: number | null; // tokens of the model calls of this turn; null when no model answered
  tokens_out: number | null;
  rule_id: string | null; // lane rule that fired this turn, if any
  rules_version: string | null;
}

export type ReplySource = "template" | "model";
export type Degradation = "model_timeout" | "tool_unavailable";

export interface ChatTurn {
  turn: number;
  reply_text: string;
  reply_language: Language;
  reply_source: ReplySource;
  buttons: ChatButton[];
  input_mode: "free_text" | "buttons_only";
}

export interface ChatResponse extends ChatTurn {
  progress: Progress;
  case_card: CustomerCaseView | null;
  lane: Lane | null;
  degraded: Degradation[];
  trace_id: string;
  trace_summary: TraceSummary;
  poll_after_ms: number | null; // > 0 while case_card is lane B in open, investigating or awaiting_analyst, or has SLA timers pending
  demo_switches: DemoSwitchState;
  synthetic: true;
}

// ---------- GET /cases/{case_id} ----------
export type CaseStatus =
  | "open"
  | "investigating"
  | "awaiting_analyst"
  | "notified"
  | "closed"
  | "reopened"
  | "resolved_in_contact" // lane A
  | "handed_off"; // lane C

// Customer-facing step of the lane B lifecycle (the card's "Investigando -> En revisión ->
// Notificado"). Derived from status by customer_view; null outside lane B.
// open|reopened -> open, investigating -> investigating, awaiting_analyst -> in_review,
// handed_off in lane B (analyst escalated) -> in_review, notified -> notified, closed -> closed.
export type LifecycleStep = "open" | "investigating" | "in_review" | "notified" | "closed";

// The reply the customer receives after an analyst decided. Only a person approves it:
// approved_by_human is always true, and `text` ends with the fixed stamp of the case language
// (template resolution_stamp: "Respuesta aprobada por una persona del equipo. En esta demo
// ningún dinero se mueve." / "Resposta aprovada por uma pessoa da equipe. Nesta demonstração
// nenhum dinheiro é movimentado.").
export interface CaseResolution {
  language: Language;
  text: string;
  sent_at: string; // ISO 8601 UTC
  approved_by_human: true;
}

export interface CustomerCharge {
  local_date: string;
  amount: string;
  currency: string;
  merchant_name: string;
  card_last4: string;
  status: string;
}

// SLA timers of a lane B case (plan v2 sections 6 and 12), scheduled when the case opens and
// deleted when an analyst decides; they only fire while the case is still open (open,
// investigating, awaiting_analyst):
// - unassigned: clock.assigned_by (+24 h) and no analyst took the case (opened it in the
//   console or decided it) -> alert in the analyst queue (sla_alerts)
// - sla_80: clock.sla_alert_at (80 % of the SLA) -> proactive notice to the customer
// - breached: clock.breach_at -> automatic escalation to the senior queue, priority high,
//   and a notice to the customer
export type SlaTimerKind = "unassigned" | "sla_80" | "breached";
export type NoticeKind = "sla_80" | "escalated";

// A proactive message of the case clock, in the case language and register. It repeats the
// promised date and never promises an outcome. At most one per kind.
export interface CaseNotice {
  kind: NoticeKind;
  text: string;
  language: Language;
  at: string; // ISO 8601 UTC, when it was sent
}

export interface CustomerCaseView {
  case_id: string; // EV-XXXXXXXX
  created_at: string;
  status: CaseStatus;
  lane: Lane | null;
  lane_reason_code: string | null; // lane rule id; the UI translates it
  subcategory: string | null;
  language: Language;
  customer_statement: string | null; // redacted, what the customer said
  charge: CustomerCharge | null; // the confirmed charge only
  expected_date: string | null; // promised resolution date
  first_response_by: string | null; // ISO timestamp
  handoff_queue: string | null; // lane C: who will contact the customer
  outcome: string | null;
  resolution: CaseResolution | null; // set when the analyst's decision is sent (status notified)
  lifecycle_step: LifecycleStep | null;
  notices: CaseNotice[]; // proactive notices of the SLA timers, oldest first; [] for most cases
  synthetic: true;
}

export interface CaseResponse {
  case: CustomerCaseView;
  // > 0 while the case is lane B open, investigating or awaiting_analyst, or while it still
  // has SLA timers pending; else null
  poll_after_ms: number | null;
}

// ---------- Errors ----------
export type ErrorCode =
  | "invalid_request"
  | "session_expired"
  | "not_authorized"
  | "conflict"
  | "session_limit"
  | "rate_limited"
  | "tool_unavailable"
  | "model_timeout"
  | "not_implemented"
  | "precondition" // 422: well formed, but the case is not in a state that allows it
  | "internal";

export interface ApiError {
  error: { code: ErrorCode; message: string; retryable: boolean };
}

// =====================================================================================
// Analyst console (docs/contrato_consola.md). Routes under /analyst/* need a Cognito JWT
// (API Gateway authorizer in the cloud; Bearer LOCAL_ANALYST_TOKEN via scripts/local_api.py
// locally). decided_by always comes from the JWT `sub`, never from the body.
// =====================================================================================

// ---------- Investigator report (INTERFACES.md #6, owner: andres) ----------
export type HypothesisName =
  | "fraud"
  | "forgotten_purchase"
  | "unfamiliar_merchant_name"
  | "duplicate"
  | "fee_error"
  | "pending_reversal";

export type Recommendation =
  | "reverse_fee"
  | "open_chargeback"
  | "block_card"
  | "explain_and_close"
  | "request_information"
  | "escalate";

export interface ReportFinding {
  claim: string;
  evidence_ids: string[]; // each one is a key of evidence_records
}

export interface ReportHypothesis {
  name: HypothesisName;
  p: number; // 0..1; each name at most once, sorted by p descending
}

export interface DraftReply {
  language: Language;
  text: string; // "generated by AI, not sent"; never promises a refund or compensation
}

// Where an evidence_id comes from (the #2 tool that returned it).
export type EvidenceKind =
  | "transaction"
  | "reversal"
  | "fee_schedule"
  | "customer_baseline"
  | "risk_evidence"
  | "digital_session"
  | "prior_contact"
  | "merchant_stats"
  | "card";

// Snapshot of one tool record, stored with the report so a citation opens without another
// route (proposal to Andrés: add evidence_records to #6). No document, address or phone.
export interface EvidenceRecord {
  kind: EvidenceKind;
  summary: string; // one line for the chip, e.g. "2026-06-14 10:05 · TIENDA TECNO SAS · 189900.00 COP"
  fields: Record<string, string | number | boolean | null>;
}

// Exactly #6 plus evidence_records. The deterministic local stub (PROVISIONAL, G2 is Andrés's)
// fills model_id "stub-g2-deterministic" and prompt_version "stub-provisional"; it is not a model.
export interface InvestigatorReport {
  report_id: string;
  case_id: string;
  created_at: string;
  findings: ReportFinding[];
  hypotheses: ReportHypothesis[];
  recommendation: Recommendation;
  confidence: number; // 0..1
  draft_reply: DraftReply;
  open_questions: string[];
  citations_valid: boolean;
  removed_claims: number;
  tool_calls: number;
  latency_ms: number;
  model_id: string;
  prompt_version: string;
  evidence_records: Record<string, EvidenceRecord>;
}

// ---------- shared by the analyst routes ----------
export type IntentClass =
  | "dispute_charge"
  | "dispute_fee"
  | "complaint_other"
  | "case_status"
  | "account_query"
  | "lost_card"
  | "human_request"
  | "out_of_scope"
  | "manipulation";

export type Priority = "high" | "normal";
export type GateAction = "accept" | "ask" | "human";
export type MatchBand = "confirm" | "choose" | "ask";
export type TxnType = "purchase" | "fee" | "reversal";
export type DecisionAction = "approve" | "edit" | "reject";
export type DecisionNext = "request_information" | "escalate";

// ---------- GET /analyst/cases ----------
// Query string, all optional: ?status=&lane=&language=&limit=&cursor=
export interface AnalystCaseListQuery {
  status?: CaseStatus;
  lane?: Lane;
  language?: Language;
  limit?: number; // 1..50, default 20
  cursor?: string; // next_cursor of the previous page, opaque
}

export interface AnalystCaseListItem {
  case_id: string;
  updated_at: string;
  status: CaseStatus;
  lane: Lane | null;
  lane_rule_id: string | null;
  queue: string | null; // internal queue id (fraud, fees, disputes, regulator, ...); the UI translates it
  priority: Priority | null;
  language: Language;
  country: string | null; // MX | CO | AR
  display_name: string; // synthetic first name
  intent_class: IntentClass | null;
  intent_p: number | null;
  subcategory: string | null;
  breach_at: string | null; // clock.breach_at; the list is sorted by it ascending, nulls last
  // SLA timers that fired, in the order unassigned, sla_80, breached; "unassigned" drops out
  // once an analyst takes the case (opens it here or decides it)
  sla_alerts: SlaTimerKind[];
  has_report: boolean;
  report_reliable: boolean | null; // null without report; false if !citations_valid or removed_claims > 1
}

export interface AnalystCaseListResponse {
  items: AnalystCaseListItem[];
  next_cursor: string | null;
  as_of: string; // server time of the listing
  poll_after_ms: number; // the console polls the queue at this pace (15000 by default)
}

// ---------- GET /analyst/cases/{case_id} ----------
// A #2 Txn as stored in the case (evidence.transaction) and in context.evidence_txns.
export interface EvidenceTxn {
  txn_id: string;
  product_id: string;
  card_last4: string | null;
  local_date: string;
  local_time: string;
  amount: string;
  currency: string;
  amount_usd: string | null;
  merchant_id: string;
  merchant_name: string;
  merchant_category: string;
  status: string;
  response_code: string;
  fraud_score: number | null;
  txn_type: TxnType;
  reversal_of: string | null;
}

export interface CaseEvidenceView {
  transaction: EvidenceTxn | null;
  product: Record<string, string | null> | null;
  app_error: Record<string, string | number | boolean | null> | null;
}

export interface CasePromise {
  expected_date: string | null;
  sla_days: number | null;
  p90_days: number | null;
}

export interface CaseAction {
  tool: string;
  args: Record<string, unknown>;
  result: unknown;
  verified_at: string | null;
}

export interface CaseHandoff {
  queue: string | null;
  priority: Priority | null;
  open_questions: string[];
  facts_verified: string[];
}

export interface CaseClock {
  assigned_by: string | null;
  first_response_by: string | null;
  sla_alert_at: string | null;
  breach_at: string | null;
}

export interface ClockEvent {
  kind: SlaTimerKind;
  fired_at: string; // when the (local) timer fired
}

export interface MatchCandidate {
  txn_id: string;
  p: number;
}

export interface CaseMatch {
  candidates: MatchCandidate[];
  chosen_id: string | null;
  p_top1: number | null;
  band: MatchBand | null;
  model_version: string | null;
}

export interface CaseIntent {
  class: IntentClass;
  p: number;
  gate_action: GateAction;
  model_version: string | null;
}

export interface CaseRiskEvidence {
  features: Record<string, unknown>;
  fraud_score: number | null;
  rule_fired: string | null;
}

export interface AnalystDecisionView {
  action: DecisionAction;
  edited: boolean; // true only for edit
  reason: string | null;
  decided_by: string; // JWT sub (locally: the claim injected by scripts/local_api.py)
  decided_at: string;
}

// The analyst's view of the case: every #3 field EXCEPT customer_id (#3 has no document,
// address or phone, and none is ever added here). No lifecycle internals (execution ARN,
// task token). Built by one server function (analyst_view), like customer_view.
export interface AnalystCaseView {
  case_id: string;
  created_at: string;
  updated_at: string | null;
  channel: "app" | "whatsapp" | "web";
  language: Language;
  segment: string | null;
  country: string | null;
  subcategory: string | null;
  intent_confidence: number | null;
  urgency_flags: string[];
  evidence: CaseEvidenceView;
  customer_statement: string | null; // redacted; what the customer said (unverified)
  lane: Lane | null;
  lane_reason: string | null; // lane rule id
  rules_version: string | null; // version of the lane rules YAML that chose the lane
  promise: CasePromise;
  actions: CaseAction[];
  handoff: CaseHandoff;
  clock: CaseClock;
  clock_events: ClockEvent[]; // SLA timers that fired, oldest first
  status: CaseStatus;
  trace_id: string | null;
  match: CaseMatch | null;
  intent: CaseIntent | null;
  risk_evidence: CaseRiskEvidence | null;
  investigation_id: string | null; // report_id of the stored report
  analyst_decision: AnalystDecisionView | null;
  labels_emitted: string[];
  resolution: CaseResolution | null;
  lifecycle_step: LifecycleStep | null;
  // The conversation of the case, REDACTED (no document, address or phone), oldest first: the
  // chat turns of the session that opened the case (from the welcome on) and every later turn,
  // plus what the analyst sent. Secondary to the structured package: the console shows it
  // folded, marked synthetic. Never another customer's or another case's turns.
  conversation: ConversationTurn[];
  synthetic: true;
}

export type ConversationRole = "customer" | "system" | "analyst";
// Who wrote the text: a template (system replies in M1), the model (none today), a person
// (the customer's own message, or the analyst's approved reply).
export type TurnSource = "template" | "model" | "human";

export interface ConversationTurn {
  role: ConversationRole;
  text: string; // already redacted; a button press is "[botón] <label>" / "[botão] <label>"
  language: Language;
  source: TurnSource;
  at: string; // ISO 8601 UTC
}

export interface AnalystProfile {
  display_name: string;
  country: string | null;
  segment: string | null;
  language: Language;
}

export interface AnalystCard {
  card_last4: string;
  status: string; // active | blocked
}

export interface PriorContact {
  contact_id: string;
  date: string;
  channel: string;
  contact_type: string; // complaint | inquiry
  subcategory: string | null;
  status: string;
}

export interface AnalystContext {
  profile: AnalystProfile;
  cards: AnalystCard[];
  evidence_txns: EvidenceTxn[]; // the disputed charge plus its duplicates, reversals and fee rows
  prior_contacts: PriorContact[];
  risk_evidence: CaseRiskEvidence | null;
  // Parts that could not be read (a data tool failed): shown as "no disponible", never as
  // an empty list that looks like "no cards" or "no prior contacts".
  unavailable: ContextPart[];
}

export type ContextPart = "cards" | "evidence_txns" | "prior_contacts";

export interface AnalystCaseDetail {
  case: AnalystCaseView;
  report: InvestigatorReport | null;
  context: AnalystContext;
  allowed_actions: DecisionAction[]; // [] unless status is awaiting_analyst; no "approve" without a report draft
  version: number; // send it back in DecisionRequest.version (optimistic lock)
}

// ---------- POST /analyst/cases/{case_id}/decision ----------
// - approve: sends report.draft_reply as is. No reply, no next. Needs a report with a draft.
// - edit: sends `reply` instead of the draft. reply and reason are required; no next.
// - reject: the recommendation is rejected. reason and next are required. reply is optional
//   and only with next=request_information (the question sent to the customer; without it
//   the server uses the request_information template); with escalate nothing is sent.
// - Every field outside these rules is a 400 invalid_request (e.g. approve with reply).
// - evidence_reviewed: must be true to approve or edit when the report is unreliable.
// - Stale version, or a second decision on an already decided case -> 409 conflict. The same
//   client_decision_id with the same body returns the stored DecisionResponse (safe retry).
// - Case not awaiting_analyst, approve without a draft, reply.language != case language,
//   unreliable report without evidence_reviewed -> 422 precondition.
export interface DecisionReply {
  language: Language;
  text: string; // 1..2000 characters
}

export interface DecisionLabels {
  intent_class?: IntentClass; // correction of the predicted class
  intent_confirmed?: boolean; // true: the predicted class is right (then no intent_class)
}

export interface DecisionRequest {
  client_decision_id: string; // uuid generated by the console
  version: number; // AnalystCaseDetail.version the analyst saw
  action: DecisionAction;
  reply?: DecisionReply;
  reason?: string; // 1..500 characters
  next?: DecisionNext;
  labels?: DecisionLabels;
  evidence_reviewed?: boolean;
}

export interface DecisionResponse {
  case_id: string;
  status: CaseStatus; // notified (approve, edit, reject + request_information) or handed_off (reject + escalate)
  analyst_decision: AnalystDecisionView;
  labels_emitted: string[];
}
